# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    param_fetcher_listener: true
    body_listener: true
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    versioning: true
    view:
        view_response_listener: 'force'